### Cadastrar Tarefa
POST http://localhost:5231/api/livros
Content-Type: application/json

{

    "titulo": "Livro 2",
    "autor" : "Autor 3",
    "categoriaId" : "2"

}


### Lista de Tarefas
GET http://localhost:5231/api/livros



### Busca pelo Id
GET http://localhost:5231/api/livros/1


### Atualizar livro

PUT http://localhost:5231/api/livros/1

{

    "titulo": "Livro 2",
    "autor" : "Autor 3",
    "categoriaId" : "2"

}

### Deletar Livro
DELETE http://localhost:5231/api/livros/1